### ISSUE TITLE
Streaming reporter should output total tests up front

### ISSUE THREAD

**Issue by meejah** [python-tap/pytest-tap#34]
It would be nice if the streaming reporter (`--tap-stream` option) printed the `1..N` line up front (instead of at the end, like now).

Using the pytest hook `pytest_runtestloop` would make this possible (but I guess it would also take a PR in `tappy` repo as well since that's what prints out the `1..N` string. If you think this is reasonable, I can submit PRs.

**Comment by mblayman** [comment]
Hi, @meejah. I'm open to this. This sounds like a good suggestion.

It might be a little tricky as you noted because the Tracker is doing all the heavy lifting. Maybe the Tracker could have a `plan` attribute that, if set, will be used instead of the `combined_line_number` that the streaming option uses instead.

As far as flag name for this plugin, I'd probably suggest something like `--tap-plan-first`. I would like the default to remain as outputting the plan at the bottom to keep a consistent behavior for any existing pytest-tap users.

**Comment by meejah** [comment]
Okay, I can do that .. I wonder if the current behavior should be considered a bug though..? All the TAP examples I saw output the "0..N" thing first, and the version 13 spec says the same thing. (I guess I'm saying: maybe no option, and the "plan" should always be output first, if available).

Either way, I'll put in a PR for the tappy repo first. Thanks!

**Comment by mblayman** [comment]
The spec is definitely clear that the plan can be first or last (http://testanything.org/tap-version-13-specification.html#the-plan).

I'm warming up to the idea of including it first since it really shouldn't matter from a TAP consumers point of view. It would probably keep the code simpler and still adhere to the spec.

I'm ok if we make it default to the top for both the streaming and combined options.

**Comment by meejah** [comment]
Ah, okay sorry I must have misread the spec.

My use-case here is that I'm running a subprocess with py.test in it, and I want to provide some kind of progress -- so I do *need* to know the total up front if "progress" is to look anything like a percentage or progress-bar or whatever.
