### ISSUE TITLE
Mismatch between docs and pytest output

### ISSUE THREAD

**Issue by nerdlem** [python-tap/pytest-tap#36]
[Current documentation](https://tappy.readthedocs.io/en/latest/producers.html#) shows this output

```tap
# TAP results for TestParser
  ⋮
ok 8 - The parser extracts an ok line.
  ⋮
1..10
```

Note the test description, which comes from

```python
class TestParser(unittest.TestCase):
    """Tests for tap.parser.Parser"""

    def test_finds_ok(self):
        """The parser extracts an ok line."""
        parser = Parser()

        line = parser.parse_line("ok - This is a passing test line.")

        self.assertEqual("test", line.category)
        self.assertTrue(line.ok)
        self.assertTrue(line.number is None)
  ⋮
```

However the output currently produced by the `pytest` plugin looks like

```
$ py.test --tap-stream tap
1..110
  ⋮
ok 41 tap/tests/test_parser.py::TestParser.test_finds_ok
  ⋮
```

Provided I'm not making any mistakes in my assessment, it looks like this functionality was dropped. Is there a way to provide a sensible TAP description?

Thanks!

**Comment by mblayman** [comment]
Thanks for the report!

The current documentation shows a sample specifically from the `nosetests` plugin. There are a couple of things different about that plugin.
* The plan (e.g., `1..110`) is calculated at the end by how many tests run. For pytest, we changed the output to put the plan first because pytest can collect all the tests it plans to run. This makes the TAP output slightly closer to the spec (as hinted at by the name "plan").
* `nose` is able to report the description in the test. Unless something has changed in the reporting hooks, `pytest` does not have that capability. The pytest-tap plugin has always produced the test name rather than the description, IIRC.

I think that means that the documentation is accurate for the capabilities of the different plugins. I hope that answered your questions.
