### ISSUE TITLE
Feature Idea - Print test names at the start of run (helpful for debugging slow running tests)

### ISSUE THREAD

**Issue by JakeTheCorn** [python-tap/pytest-tap#65]
I really like the plugin so far.

While debugging some tests... I found one that was long running....

BUT! I had to look at code to do so, and I would rather my test feedback tell me about it.

currently my test output is like..

```
ok 1 apps/my_app/tests/some_test.py::my_test_name
```

and I would like to have the option of....

```
1 apps/my_app/tests/some_test.py::my_test_name ... ok
```

in other words

```
<test_num> <test_identifier(path)> <has_begun_run> <status>
```

instead of

```
<status> <test_num> <test_identifier(path)>
```

That way I could know which one was running and recognize hanging more easily.

Any thoughts?

thanks much!

**Comment by mblayman** [comment]
Hi, @JakeTheCorn. My goal with pytest-tap (and the underlying tappy library that powers the TAP output) is to adhere to the TAP specification strictly. The specification only accepts lines where the status is at the beginning of the line.

You can see in the spec that the status "must be at the beginning of the line" (https://testanything.org/tap-version-14-specification.html#test-status-ok-or-not-ok).

Since that is a requirement of the spec and the project is focused on implementing the spec and nothing more, this is not a feature that I'm interested in adding. I hope that makes sense.
